SchoolManagement/urls.py
from django.contrib import admin
from django.urls import path

from myUser import views
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    url(r'^$',views.base),
    url(r'^',include('social_django.urls',namespace="social")),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/$',views.usersignup),
    url(r'^verifyuser/$',views.verify),
    url(r'^login/$',views.login),
    url(r'^manager/',include('manager.urls')),
    url(r'^principal/',include('principal.urls')),
    url(r'^teacher/', include('teacher.urls')),
    url(r'^clerical/', include('clerical.urls')),
    url(r'^student/', include('students.urls')),
    url(r'^error404/$',views.error404),
    url(r'^logout/$',views.logout),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manager/urls.py
from manager import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

app_name = 'manager'
urlpatterns = [
    url(r'^passwordchange/$', views.passwordchange, name="passch"),
    url(r'^home/$', views.manager),
    url(r'^profile/$', views.managerprofile, name="mprofile"),
    url(r'^addprincipal/$', views.createprincipal, name="addprinci"),
    url(r'^viewprincipal/$', views.viewprincipal, name="viewprincipal"),
    url(r'^createteacher/$', views.createteacher, name="createteacher"),
    url(r'^viewteacher/$', views.viewteacher, name="viewteacher"),
    url(r'^updateteacher/$', views.updateteacher, name="updateteacher"),
    url(r'^deleteteacher/$', views.deleteteacher, name="deleteteacher")





] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myUser/urls.py
from myUser import views
from django.conf.urls import url

app_name = 'myUser'

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from principal.models import Principle

class PrincipleForm(forms.ModelForm):
    class Meta():
        model =Principle
        exclude =["name","email","gender","qualification","password",
                  "dob","doj","dol","address","mobile","status","session","image","last_login_time",
                  "last_login_date","last_logout","role","otp","otp_date_time","verify_link"]

manager/views.py
from django.shortcuts import render,redirect,HttpResponse
from miscellaneous import emailsend,myconstants
from authorize import authcheck
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.hashers import make_password,check_password
from authorize import authcheck
from myUser.models import UserSignup
from principal.models import Principle
from teacher.models import TeacherDetail
from manager.forms import PrincipleForm
from teacher.forms import TeacherForm
from myUser.forms import UserSignupForm
import datetime as dt

def passwordchange(request):
    emailid = request.session['emailid']
    data = UserSignup.objects.get(userEmail=emailid)
    if request.method=="POST":
        oldpassword = request.POST["op"]
        newpassword = request.POST["np"]
        connewpassword = request.POST["cnp"]
        auth = check_password(oldpassword, data.userPassword)
        if auth == True :
            if newpassword == connewpassword :
                password = make_password(newpassword)
                updateD = UserSignup(userEmail=emailid, userPassword = password)
                updateD.save(update_fields=["userPassword"])
                return HttpResponse("<h1>Password Change Successful.</h1>")
            else:
                return HttpResponse("<h1>New password and confirm password doesn't match</h1>")
        else :
            return HttpResponse("<h1>Please enter correct old password</h1>")
    return render(request,"passwordchange.html",{'d':data})


def manager(request):
    try:
        authdata = authcheck.authentication(request.session['Authentication'],request.session['roleid'],myconstants.MANAGER)
        if authdata== True :
            emailid = request.session['emailid']
            data = UserSignup.objects.get(userEmail=emailid)
            return render(request,"index.html",{'d':data,'t':'Management'})
        else :
            authinfo,message = authdata
            if message == "Invalid_User":
                return redirect("/error404/?value=2")
            elif message == "not_login" :
                return redirect("/error404/?value=3")
    except:
        return redirect("/error404/?value=1")

def managerprofile(request):
    emailid = request.session['emailid']
    data = UserSignup.objects.get(userEmail = emailid)
    return render(request,"profile.html",{'d':data})


def createprincipal(request):
    pridata = Principle.objects.all()
    if len(pridata) != 0 :
        checkactive = 0
        for i in pridata :
            print(i.status)
            if i.status == 1:
                checkactive = checkactive + 1
        if checkactive != 0 :
            return render(request,"CreatePrinci.html",{'d':True})

    elif request.method == "POST":
        form = PrincipleForm(request.POST)
        f = form.save(commit=False)
        try:
            if request.FILES["img1"]:
                my_file = request.FILES["img1"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                img1 = fs.url(file_name)
                img1 = my_file.name
        except:
            pass

        f.name = request.POST["pn"]
        f.email = request.POST["pe"]
        f.gender = request.POST["pg"]
        f.qualification = request.POST["pq"]
        f.password = make_password(request.POST["pp"])
        f.dob = request.POST["pd"]
        x= str(dt.date.today())
        f.doj = x
        f.address = request.POST["pa"]
        f.mobile = request.POST["pm"]
        # f.status = True
        otp, y = emailsend.OtpSend()
        year =y[0:4]
        nextyr =int(year)+1
        session = str(year) + "-" + str(nextyr)
        f.session = session
        f.image = img1
        # f.last_login_time = request.POST["t3"]
        # f.last_login_date = request.POST["t3"]
        # f.last_logout = request.POST["t3"]
        f.otp = otp
        f.otp_date_time = y
        email = request.POST["pe"]
        token = email[0:5] + request.POST['pm'][4:9] + otp
        token = make_password(token)
        token = token.replace("+", "")
        f.userToken = token
        confirmationlink = "http://127.0.0.1/verifyuser/?email=" + email + "&token=" + token
        f.verify_link = confirmationlink
        f.role_id = 2
        f.save()
     #to update in common signup database
        form1 = UserSignupForm(request.POST)
        f = form1.save(commit=False)
        f.userFullName= request.POST["pn"]
        f.userEmail = request.POST["pe"]
        f.userPassword = make_password(request.POST["pp"])
        f.userMobile = request.POST["pm"]
        f.userState = request.POST["pa"]
        f.userOTP = otp
        f.otpTime = y
        f.userToken = token
        f.isVerified = False
        f.confirmationLink = confirmationlink
        f.isActive = True
        f.roleId_id = 2
        f.save()
        emailsend.sendemail("Confirmation Link", email, confirmationlink)
        return render(request, "CreatePrinci.html", {'success': True})
    return render(request, "CreatePrinci.html")

def viewprincipal(request):
    data = Principle.objects.all()
    return render(request,"viewprincipal.html",{'d': data})


def createteacher(request):
    if request.method == "POST":
        form=TeacherForm(request.POST)
        f=form.save(commit=False)
        try:
            if request.FILES["timage"]:
                my_file = request.FILES["timage"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                timage = fs.url(file_name)
                timage= my_file.name
        except:
            pass
        f.name = request.POST["tname"]
        f.email = request.POST["temail"]
        f.gender = request.POST["tgender"]
        f.subject = request.POST["tsubject"]
        f.qualification = request.POST["tqualification"]
        f.password = request.POST["tpassword"]
        f.dob = request.POST["tdob"]
        f.doj = str(dt.date.today())
        f.address = request.POST["taddress"]
        f.mobile = request.POST["tmobile"]
        currentYear=dt.date.today()
        s=currentYear.year
        f.session = s
        f.image = timage
        # f.last_login_time =
        # f.last_login_date =
        # f.last_logout =
        f.role_id = 3
        otp ,y = emailsend.OtpSend()

        email = request.POST["temail"]
        token = email[0:5] + request.POST['tmobile'][4:9] + otp
        token = make_password(token)
        token = token.replace("+", "")

        confirmationlink = "http://127.0.0.1/verifyuser/?email=" + email + "&token=" + token
        f.class_asn_id = 9
        f.status = True
        f.save()
        # to update in common signup database
        form1 = UserSignupForm(request.POST)
        f = form1.save(commit=False)
        f.userFullName = request.POST["tname"]
        f.userEmail = request.POST["temail"]
        f.userPassword = make_password(request.POST["tpassword"])
        f.userMobile = request.POST["tmobile"]
        f.userState = request.POST["taddress"]
        f.userOTP = otp
        f.otpTime = y
        f.userToken = token
        f.isVerified = False
        f.confirmationLink = confirmationlink
        f.isActive = True
        f.roleId_id = 3
        f.save()
        emailsend.sendemail("Confirmation Link", email, confirmationlink)
        return render(request,"createteacher.html",{'success':True})
    return render(request,"createteacher.html")

def viewteacher(request):
    data=TeacherDetail.objects.all()

    return render(request,"viewteacher.html",{'d': data})

def updateteacher(request):
    email=request.GET["id"]
    data = TeacherDetail.objects.get(email=email)
    if request.method == "POST":
        timage=request.FILES["timage"]
        form=TeacherForm(request.POST)
        img=timage
        try:
            if request.FILES["timage"]:
                my_file = request.FILES["timage"]
                fs = FileSystemStorage()
                file_name = fs.save(my_file.name, my_file)
                img = fs.url(file_name)
                img = my_file
        except:
            pass
        name = request.POST["tname"]
        email = email
        gender = request.POST["tgender"]
        qualifiaction = request.POST["tqualification"]
        password = make_password(request.POST["tpassword"])
        dob = request.POST["tdob"]
        doj = request.POST["tdoj"]
        dol = request.POST["tdol"]
        address = request.POST["taddress"]
        mobile = request.POST["taddress"]
        session = request.POST["tsession"]
        image = img
        updatedata = TeacherDetail(email=email,name=name,gender=gender,qualifiaction=qualifiaction,
                             password=password,dob=dob,doj=doj,dol=dol, address=address,mbile=mobile,session=session,image=image)
        updatedata.save(update_fields=["name","gender","qualification","password","dob","doj","dol","address", "mobile","image"])
        return redirect('/manager/viewteacher')
    return render(request,"updateteacher.html",{'d':data})


def deleteteacher(request):
    email=request.GET["id"]
    data=TeacherDetail.objects.get(email=email)
    data.delete()
    return redirect('/manager/viewteacher')

manager/templates/CreatePrinci.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Principal account</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
{% extends 'index.html' %}
{% block content %}
<div align="center">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        {% if d %}
        <h1>Active Principal is already there</h1>
        {% else %}
<table border="2px" height="500px" width="400px">
    <tr>
        <td>
    <label>Name :</label>
    <input type="text" id="pn" name="pn"><br>
        </td>
    </tr>
    <tr>
        <td>
    <label>Email : </label>
    <input type="email" id="pe" name="pe"><br>
        </td>
    </tr>
    <tr><td>
    <label>Gender : </label>

    <input type="radio"  name="pg" value="Male">Male

    <input type="radio"  name="pg" value="Female">Female

    <input type="radio"  name="pg" value="Other">Otherss
        </td>
    </tr>
    <tr>
        <td>
    <label>Qualifications :</label>

    <input type="text" id="pq" name="pq"><br>
        </td>
    </tr>
    <tr>
        <td>
    <label>DOB : </label>

    <input type="date" id="pd" name="pd"><br>
        </td>
    </tr>
    <tr>
        <td>
    <label>Address : </label>

    <input type="text" id="pa" name="pa"><br>
        </td>
    </tr>
    <tr>
        <td>
    <label>Mobile :</label>

            <input type="number" id="pm" name="pm"><br>
        </td>
    </tr>
    <tr>
        <td>
            <label>Password :</label>

            <input type="password" id="pp" name="pp"><br>
        </td>
    </tr>
<tr>
    <td>
    <label>Upload Image :</label>

            <input type="file" id="img1" name="img1"><br>
        </td>
    </tr>
    <tr>
        <td align="center">
            <input  type="submit" value="Submit">
        </td>
    </tr>
</table>

        {% endif %}
    </form>

    <a href="/manager/viewprincipal/">View Principal </a>
</div>
 {% endblock %}
 </body>
</html>

manager/templates/createteacher.html
{% extends 'index.html' %}
{% block content %}
<h1 style="text-align:center;">Create Teacher Account </h1>
<br>
<form method="post" enctype="multipart/form-data" align="center">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert('Details Updated Successfully');
    </script>
    {% endif %}
<div class="form-row">
<div class="form-group col-md-6">
<label for="name"> Full Name</label>
<input type="text" class="form-control" id="tname" name="tname" style="text-align" required placeholder="Name here">
</div>
<div class="form-group col-md-6">
<label for="email">Email</label>
<input type="text" class="form-control" id="temail" name="temail" value="@gmail.com" style="text-align" required="">
</div>
</div>


<div class="form-row">
<div class="form-group col-md-3">
<label for="password">Password</label>
<input type="text" class="form-control" id="tpassword"  name="tpassword" style="text-align" required="">
</div>
<div class="form-group col-md-3">
<label for="qualification">Qualification</label>
    <select class="form-control" id="tqualification"  name="tqualification" style="text-align;padding:8px " required="">
        <option>Btech/BE</option>
        <option>Diploma</option>
        <option>MSC</option>
        <option>MA</option>
        <option>MCOM</option>
        <option>BSC</option>
        <option>BA</option>
        <option>BCOM</option>
        <option>PHD</option>
        <option>Mtech/ME</option>
        <option>B.Ed</option>
        <option>JBT</option>

    </select>
</div>
    <div class="form-group col-md-3">
<label for="subject">Subject</label>
    <select class="form-control" id="tsubject"  name="tsubject" style="text-align;padding:8px " required="">
        <option>English</option>
        <option>Hindi</option>
        <option>Mathematics</option>
        <option>Science</option>
        <option>Social Science</option>
        <option>Sanskrit</option>
        <option>Physics</option>
        <option>Maths(non medical</option>
        <option>Biology(medical)</option>
        <option>Chemistry</option>
        <option>Physical</option>
        <option>IT(+1)</option>
        <option>IP(+2)</option>
        <option>Economics</option>
        <option>Business Studies</option>
        <option>Hindi(10+1+2)</option>
        <option>Accountancy(10+1+2)</option>
        <option>English(10+1+2)</option>
        <option>Geography(10+1+2)</option>
        <option>Political Science(10+1+2)</option>
        <option>History(10+1+2)</option>
        <option>Psycology(10+1+2)</option>

   </select>
</div>

<div class="form-group col-md-3">
<label for="mobile">Mobile</label>
<input type="text" class="form-control" id="tmobile"  name="tmobile" value="+91" style="text-align" required="">
</div>
</div>


<div class="form-row">
    <div class="form-group col-md-3">
    <div class="form-check form-check-inline">
        <label for="gender">Gender</label></br>
        <input type="radio" id="tgenderm" name="tgender" value="male">Male &nbsp;&nbsp;
        <input type="radio" id="tgenderf" name="tgender" value="female">Female &nbsp;&nbsp;
        <input type="radio" id="tgendero" name="tgender" value="others">Others
    </div>
    </div>
    <div class="form-group col-md-3">
<label for="session">Session</label>
<input type="date" class="form-control" id="tsession" name="tsession" value="2010" style="text-align" required="">
</div>
<div class="form-group col-md-3">
<label for="dob">Date of Birth</label>
<input type="date" class="form-control" id="tdob" name="tdob" style="text-align" required="">
</div>
<div class="form-group col-md-3">
<label for="doj">Date of Joining</label>
<input type="date" class="form-control" id="tdoj" name="tdoj" style="text-align" required="">
</div>
</div>

<div class="form-row">
<div class="form-group col-md-6">
<label for="address">Address</label>
<input type="text" class="form-control" id="taddress" name="taddress" style="text-align" required="">
</div>

</div>
<div class="form-group col-md-6">
<div class="custom-file">

<label class="custom-file-la bel" for="image" aria-describedby="inputGroupFileAddon02">Choose Image</label>
    <input type="file" id="timage" name="timage">
</div>
</div>

<br>
<div align="center" class="form-group col-md-12">
<input type="submit"  value="Submit">
</div>
</form>
<br>
<br>
<div align="center" class="form-group col-md-12">

    <a  href="/manager/viewteacher/">View Teacher Records</a>
</div>
{% endblock %}

manager/templates/manager.html
{% extends 'base.html' %}

{% block content %}

<h1>Manager Login</h1>
<a href="{% url 'manager:passch'%}"><button>Change Password</button></a>


<a href="{% url 'manager:mprofile' %}"><button>View Profile</button></a>
<hr>
<a href="/logout/"><button>Logout</button></a>




{% endblock %}

manager/templates/passwordchange.html
{% extends 'index.html' %}

{% block content %}

<form  method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
<div id="pass" name="pass">
<h1>Change Password</h1><br>
<label>old password </label>
<input type="password" id="op" name="op"><br>
<label>New Password</label>
<input type="password" id="np" name="np"><br>
<label>Confirm New Password</label>
<input type="password" id="cnp" name="cnp"><br>
<input type="submit" id="b1" name="b1" value="Submit">
</div>
</form>


{% endblock %}

manager/templates/profile.html
{% extends 'index.html' %}
{% block content %}
<div>
    {% if d %}
    <label>Full Name</label>
    <input type="text" value="{{d.userFullName}}"><br>

    <label>Email</label>
    <input type="text" value="{{d.userEmail}}"><br>

    <label>Mobile Number</label>
    <input type="text" value="{{d.userMobile}}"><br>

    <label>State</label>
    <input type="text" value="{{d.userState}}"><br>
    {% endif %}
</div>
{% endblock %}

manager/templates/updateteacher.html
{% extends 'index.html' %}
{% block content %}
<h1 style="text-align:center;">Create Teacher Account </h1>
</br>
<form method="post" enctype="multipart/form-data" align="center">
    {% csrf_token %}
    {% if success %}
    <script type="text/javascript">
        alert('Details Updated Successfully');
    </script>
    {% endif %}
    {% if d %}
<div class="form-row">
<div class="form-group col-md-6">
<label for="name"> Full Name</label>
<input type="text" class="form-control" id="tname" name="tname" style="text-align" value="{{d.name}}" required placeholder="Name here">
</div>
<div class="form-group col-md-6">
<label for="email">Email</label>
<input type="text" class="form-control" id="temail" name="temail" value="{{d.email}}" style="text-align" required="">
</div>
</div>


<div class="form-row">
<div class="form-group col-md-3">
<label for="password">Password</label>
<input type="text" class="form-control" id="tpassword"  name="tpassword" style="text-align" required="">
</div>
<div class="form-group col-md-3">
<label for="qualification">Qualification</label>
    <select class="form-control" id="tqualification"  name="tqualification" value="{{d.tqualification}}" style="text-align" required="">
        <option>Btech/BE</option>
        <option>Diploma</option>
        <option>MSC</option>
        <option>MA</option>
        <option>MCOM</option>
        <option>BSC</option>
        <option>BA</option>
        <option>BCOM</option>
        <option>PHD</option>
        <option>Mtech/ME</option>
        <option>B.Ed</option>
        <option>JBT</option>

    </select>
</div>
  <div class="form-group col-md-3">
<label for="subject">Subject</label>
    <select class="form-control" id="tsubject"  name="tsubject" value="{{d.subject}}" style="text-align;padding:8px " required="">
        <option>English</option>
        <option>Hindi</option>
        <option>Mathematics</option>
        <option>Science</option>
        <option>Social Science</option>
        <option>Sanskrit</option>
        <option>Physics</option>
        <option>Maths(non medical</option>
        <option>Biology(medical)</option>
        <option>Chemistry</option>
        <option>Physical</option>
        <option>IT(+1)</option>
        <option>IP(+2)</option>
        <option>Economics</option>
        <option>Business Studies</option>
        <option>Hindi(10+1+2)</option>
        <option>Accountancy(10+1+2)</option>
        <option>English(10+1+2)</option>
        <option>Geography(10+1+2)</option>
        <option>Political Science(10+1+2)</option>
        <option>History(10+1+2)</option>
        <option>Psycology(10+1+2)</option>

   </select>
</div>

<div class="form-group col-md-3">
<label for="mobile">Mobile</label>
<input type="text" class="form-control" id="tmobile"  name="tmobile" value="{{d.mobile}}" style="text-align" required="">
</div>
</div>


<div class="form-row">
    <div class="form-group col-md-6">
    <div class="form-check form-check-inline">
        <label for="gender">Gender</label></br>
        <input type="radio" id="tgenderm" name="tgender" value="male">Male &nbsp;&nbsp;
        <input type="radio" id="tgenderf" name="tgender" value="female">Female &nbsp;&nbsp;
        <input type="radio" id="tgendero" name="tgender" value="others">Others
    </div>
    </div>
<div class="form-group col-md-3">
<label for="dob">Date of Birth</label>
<input type="date" class="form-control" id="tdob" name="tdob" value="{{d.dob}}" style="text-align" required="">
</div>
<div class="form-group col-md-3">
<label for="doj">Date of Joining</label>
<input type="date" class="form-control" id="tdoj" name="tdoj" value="{{d.doj}}" style="text-align" required="">
</div>
</div>
<div class="form-row">
<div class="form-group col-md-6">
<label for="address">Address</label>
<input type="text" class="form-control" id="taddress" name="taddress" value="{{d.address}}" style="text-align" required="">
</div>
<div class="form-group col-md-3">
<label for="session">Session</label>
<input type="date" class="form-control" id="tsession" name="tsession" value="{{d.session}}" style="text-align" required="">
</div>
    <div class="form-group col-md-3">
<label for="dol">Date Of Leaving</label>
<input type="date" class="form-control" id="tdol" name="tdol" style="text-align">
</div>
</div>
<div class="form-group col-md-6">
<div class="custom-file">
<input type="file" class="custom-file-input" style="text-align" id="timage"><img height="60px" width="60px" src="/media/{{d.image}}">
<label class="custom-file-la bel" for="image" aria-describedby="inputGroupFileAddon02">Choose Image</label>
</div>
</div>

<br>
<div align="center" class="form-group col-md-12">
<input type="submit"  value="Submit">
</div>
</form>
<br>
<br>
<div align="center" class="form-group col-md-12">

    <a  href="/manager/viewteacher/">View Teacher Records</a>
</div>
{% endif %}
{% endblock %}

manager/templates/viewprincipal.html
<head>
    <meta charset="UTF-8">
    <title>Principal Record</title>
</head>
<body>
{% extends 'index.html' %}
{% csrf_token %}
{% block content %}
<div>
<table class="table" border="2px"  align="center" cellspacing="50px">
      <thead class="thead-dark" style="background-color:black;font-size:20px;">
    <tr>
        <th scope="col" >Name</th>
        <th scope="col">Email</th>
        <th scope="col">Gender</th>
        <th scope="col">Qualification</th>
        <th scope="col">Date Of Birth</th>
        <th scope="col">Date Of Joining</th>
        <th scope="col">Mobile</th>
        <th scope="col">Address</th>
        <th scope="col">Session</th>
        <th scope="col">Image</th>

    </tr>
      </thead>
 {% if d %}
{% for i in d %}

    <tr>
        <td>{{i.email}}</td>
        <td>{{i.name}}</td>
        <td>{{i.gender}}</td>
        <td>{{i.qualification}}</td>
        <td>{{i.dob}}</td>
        <td>{{i.doj}}</td>
        <td>{{i.mobile}}</td>
        <td>{{i.address}}</td>
        <td>{{i.session}}</td>
        <td><img height="60px" width="60px" src="/media/{{i.image}}"></td>

    </tr>
{% endfor %}
{% endif %}
</table>
</div>

{% endblock %}
</body>

manager/templates/viewteacher.html
<head>
    <meta charset="UTF-8">
    <title>View Teacher Records</title>
</head>
<body>
{% extends 'index.html' %}
{% csrf_token %}
{% block content %}
<div>
<table class="table" border="2px"  align="center" cellspacing="50px">
      <thead class="thead-dark" style="background-color:black;font-size:20px;">
    <tr>
        <th scope="col" style="text-color:white;">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Gender</th>
        <th scope="col">Qualification</th>
        <th scope="col">Date Of Birth</th>
        <th scope="col">Date Of Joining</th>
        <th scope="col">Mobile</th>
        <th scope="col">Address</th>
        <th scope="col">Session</th>
        <th scope="col">Image</th>
        <th scope="col">Action</th>
        <th scope="col">Delete</th>
    </tr>
      </thead>
 {% if d %}
{% for i in d %}

    <tr>
        <td>{{i.name}}</td>
        <td>{{i.email}}</td>
        <td>{{i.gender}}</td>
        <td>{{i.qualification}}</td>
        <td>{{i.dob}}</td>
        <td>{{i.doj}}</td>
        <td>{{i.mobile}}</td>
        <td>{{i.address}}</td>
        <td>{{i.session}}</td>
        <td><img height="60px" width="60px" src="/media/{{i.image}}"></td>
        <td><a href="/manager/updateteacher/?id={{i.email}}">Edit</a></td>
        <td><a href="/manager/deleteteacher/?id={{i.email}}">Delete</a></td>

    </tr>
{% endfor %}
{% endif %}
</table>
</div>

{% endblock %}
</body>